# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_generated import autocomplete_pb2 as autocomplete__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in autocomplete_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AutocompleteServiceStub:
    """── Service definition ─────────────────────────────────────────
    This is the contract between Router and each Shard.
    Router calls these methods, Shard implements them.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/autocomplete.AutocompleteService/Search',
                request_serializer=autocomplete__pb2.SearchRequest.SerializeToString,
                response_deserializer=autocomplete__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/autocomplete.AutocompleteService/Health',
                request_serializer=autocomplete__pb2.HealthRequest.SerializeToString,
                response_deserializer=autocomplete__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.InsertWord = channel.unary_unary(
                '/autocomplete.AutocompleteService/InsertWord',
                request_serializer=autocomplete__pb2.WordRequest.SerializeToString,
                response_deserializer=autocomplete__pb2.WordResponse.FromString,
                _registered_method=True)
        self.DeleteWord = channel.unary_unary(
                '/autocomplete.AutocompleteService/DeleteWord',
                request_serializer=autocomplete__pb2.WordRequest.SerializeToString,
                response_deserializer=autocomplete__pb2.WordResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/autocomplete.AutocompleteService/GetStats',
                request_serializer=autocomplete__pb2.StatsRequest.SerializeToString,
                response_deserializer=autocomplete__pb2.StatsResponse.FromString,
                _registered_method=True)


class AutocompleteServiceServicer:
    """── Service definition ─────────────────────────────────────────
    This is the contract between Router and each Shard.
    Router calls these methods, Shard implements them.

    """

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutocompleteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=autocomplete__pb2.SearchRequest.FromString,
                    response_serializer=autocomplete__pb2.SearchResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=autocomplete__pb2.HealthRequest.FromString,
                    response_serializer=autocomplete__pb2.HealthResponse.SerializeToString,
            ),
            'InsertWord': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertWord,
                    request_deserializer=autocomplete__pb2.WordRequest.FromString,
                    response_serializer=autocomplete__pb2.WordResponse.SerializeToString,
            ),
            'DeleteWord': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWord,
                    request_deserializer=autocomplete__pb2.WordRequest.FromString,
                    response_serializer=autocomplete__pb2.WordResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=autocomplete__pb2.StatsRequest.FromString,
                    response_serializer=autocomplete__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autocomplete.AutocompleteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autocomplete.AutocompleteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AutocompleteService:
    """── Service definition ─────────────────────────────────────────
    This is the contract between Router and each Shard.
    Router calls these methods, Shard implements them.

    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocomplete.AutocompleteService/Search',
            autocomplete__pb2.SearchRequest.SerializeToString,
            autocomplete__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocomplete.AutocompleteService/Health',
            autocomplete__pb2.HealthRequest.SerializeToString,
            autocomplete__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocomplete.AutocompleteService/InsertWord',
            autocomplete__pb2.WordRequest.SerializeToString,
            autocomplete__pb2.WordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocomplete.AutocompleteService/DeleteWord',
            autocomplete__pb2.WordRequest.SerializeToString,
            autocomplete__pb2.WordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocomplete.AutocompleteService/GetStats',
            autocomplete__pb2.StatsRequest.SerializeToString,
            autocomplete__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BKTreeServiceStub:
    """── BK-Tree Service ───────────────────────────────────────────
    Implemented by the dedicated BK-Tree microservice
    Called by the router for all fuzzy search requests
    Completely independent of shard health

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FuzzySearch = channel.unary_unary(
                '/autocomplete.BKTreeService/FuzzySearch',
                request_serializer=autocomplete__pb2.FuzzySearchRequest.SerializeToString,
                response_deserializer=autocomplete__pb2.FuzzySearchResponse.FromString,
                _registered_method=True)
        self.InsertWord = channel.unary_unary(
                '/autocomplete.BKTreeService/InsertWord',
                request_serializer=autocomplete__pb2.WordRequest.SerializeToString,
                response_deserializer=autocomplete__pb2.WordResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/autocomplete.BKTreeService/Health',
                request_serializer=autocomplete__pb2.HealthRequest.SerializeToString,
                response_deserializer=autocomplete__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/autocomplete.BKTreeService/GetStats',
                request_serializer=autocomplete__pb2.StatsRequest.SerializeToString,
                response_deserializer=autocomplete__pb2.BKStatsResponse.FromString,
                _registered_method=True)


class BKTreeServiceServicer:
    """── BK-Tree Service ───────────────────────────────────────────
    Implemented by the dedicated BK-Tree microservice
    Called by the router for all fuzzy search requests
    Completely independent of shard health

    """

    def FuzzySearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BKTreeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FuzzySearch': grpc.unary_unary_rpc_method_handler(
                    servicer.FuzzySearch,
                    request_deserializer=autocomplete__pb2.FuzzySearchRequest.FromString,
                    response_serializer=autocomplete__pb2.FuzzySearchResponse.SerializeToString,
            ),
            'InsertWord': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertWord,
                    request_deserializer=autocomplete__pb2.WordRequest.FromString,
                    response_serializer=autocomplete__pb2.WordResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=autocomplete__pb2.HealthRequest.FromString,
                    response_serializer=autocomplete__pb2.HealthResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=autocomplete__pb2.StatsRequest.FromString,
                    response_serializer=autocomplete__pb2.BKStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autocomplete.BKTreeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autocomplete.BKTreeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BKTreeService:
    """── BK-Tree Service ───────────────────────────────────────────
    Implemented by the dedicated BK-Tree microservice
    Called by the router for all fuzzy search requests
    Completely independent of shard health

    """

    @staticmethod
    def FuzzySearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocomplete.BKTreeService/FuzzySearch',
            autocomplete__pb2.FuzzySearchRequest.SerializeToString,
            autocomplete__pb2.FuzzySearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocomplete.BKTreeService/InsertWord',
            autocomplete__pb2.WordRequest.SerializeToString,
            autocomplete__pb2.WordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocomplete.BKTreeService/Health',
            autocomplete__pb2.HealthRequest.SerializeToString,
            autocomplete__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocomplete.BKTreeService/GetStats',
            autocomplete__pb2.StatsRequest.SerializeToString,
            autocomplete__pb2.BKStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
